### ISSUE TITLE
libjvm.dylib in different folder on macOS Catalina

### ISSUE THREAD

**Issue by AljoschaP** [CoatiSoftware/Sourcetrail#757] opened 2019-11-19 13:11 UTC
According to the documentation, libjvm.dylib is located in:  

`/Library/Java/JavaVirtualMachines/<jdk_version>/Contents/Home/jre/lib/jli/libjvm.dylib`

but OpenJDK seems to put it in [1]:

`/Library/Java/JavaVirtualMachines/<jdk_version>/Contents/Home/lib/server/libjvm.dylib `

Maybe there should be a hint in the documentation for our OpenJDK fellows :-) 

OpenJDK: 

- openjdk 12.0.2 2019-07-16

Mac: 

- System Version: macOS 10.15 (19A583)

- Kernel Version: Darwin 19.0.0

[1] https://stackoverflow.com/questions/46768684/what-is-the-standard-location-for-libjvm-so-and-libjvm-dylib-in-java-9

**Comment by mlangkabel** [comment] 2019-11-19 17:14
I think there are different version of the `libjvm.dylib`, some of which can be used with Sourcetrail and some cannot. Did you try using the library from 
```
/Library/Java/JavaVirtualMachines/<jdk_version>/Contents/Home/lib/server/libjvm.dylib
```
to index some Java code? Did it work?

**Comment by gtexpanse** [comment] 2019-11-21 02:34
In Oracle jdk1.8.0_172, the path is:
`/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre/lib/server/libjvm.dylib`
and it works good.

**Comment by AljoschaP** [comment] 2019-11-21 08:04
> I think there are different version of the `libjvm.dylib`, some of which can be used with Sourcetrail and some cannot. Did you try using the library from
> 
> ```
> /Library/Java/JavaVirtualMachines/<jdk_version>/Contents/Home/lib/server/libjvm.dylib
> ```
> 
> to index some Java code? Did it work?

Yes, it does.

**Comment by egraether** [comment] 2020-06-01 21:00
Duplicate of #955 

The actual issue was that our Java Path detection on macOS did not support the latest JDK directory structure. We now consider additional paths, preferably:
```
/Library/Java/JavaVirtualMachines/<jdk_version>/Contents/MacOS/libjli.dylib
```

I updated Java Path detection and docs for macOS with #1031

**Closed by egraether** 2020-06-01 21:00 UTC
Labels: Java, Mac, documentation
