### ISSUE TITLE
unable to locate Java on this machine. 

### ISSUE THREAD

**Issue by suood** [CoatiSoftware/Sourcetrail#963] opened 2020-04-04 20:16 UTC
I got an error.
ENV: 
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
JRE_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre
CLASSPATH=.:$JAVAHOME/lib/dt.jar:$JAVAHOME/lib/tools.jar:$JRE_HOME/lib/rt.jar
export JAVA_HOME
export JRE_HOME
export CLASSPATH

sourcetrail version :2020.1.117 64bit 
Could not load library "/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/jli/libjli.dylib"
Sourcetrail was unable to locate Java on this machine. Please make sure to provide the correct Java Path in the preferences.  Error: Could not load library "/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/jli/libjli.dylib"
![image](https://user-images.githubusercontent.com/2971719/78460531-2a2e5a00-76f4-11ea-8fb2-d80b7cfa5517.png)

**Comment by mlangkabel** [comment] 2020-04-06 07:52
Looks like this is a duplicate of #955. Please continue discussing there.

**Comment by mlangkabel** [comment] 2020-04-06 07:52
Oh, you already commented there.

**Closed by mlangkabel** 2020-04-06 07:52 UTC
