### ISSUE TITLE
Does Sourcetrail the C# language?

### ISSUE THREAD

**Issue by it19862** [CoatiSoftware/Sourcetrail#1139] opened 2021-02-13 10:00 UTC
Does Sourcetrail the C# language?
Are you planning to make Sourcetrail support the C#language?

**Comment by mlangkabel** [comment] 2021-02-17 18:00
Thanks for asking. I think this is a duplicate of #398. Closing now ;)

**Closed by mlangkabel** 2021-02-17 18:00 UTC
