### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by alex-bender** [CoatiSoftware/Sourcetrail#1169] opened 2021-03-26 10:14 UTC
Hello,
Do you have any plans to integrate the indexed code with git repository?
Would be great to have an ability to check who's commiter or at least which commit hash current code is introduced by.
Thanks

**Comment by mlangkabel** [comment] 2021-03-30 18:47
Thanks for the suggestion. I think there is already an issue open for this one. Looks like a duplicate of #588.

**Closed by mlangkabel** 2021-03-30 18:47 UTC

**Comment by alex-bender** [comment] 2021-03-30 18:51
I've investigated a bit, but looks like not too much. Thanks for replying!
