### ISSUE TITLE
New Project location invalid for folders with dot in it

### ISSUE THREAD

**Issue by peterkline-es** [CoatiSoftware/Sourcetrail#992] opened 2020-04-28 16:28 UTC
Sourcetrail Version: 2020.1.117
OS: OSX 10.14.5

I have upgraded from the last version of 2019 and I am no longer able to add new project source groups to any folder under my User directory.  User name is `First.Last` so /Users/First.Last/project does not work.  This used to work and it still works for projects I have already created but not for new projects.

I get a UI modal stating:  `The specified location seems to be invalid.  Please check the characters used in the path.`

Application Log from start of application to trying to add source group.
[log_2020-04-28_12-17-50 copy.txt](https://github.com/CoatiSoftware/Sourcetrail/files/4547161/log_2020-04-28_12-17-50.copy.txt)

**Comment by mlangkabel** [comment] 2020-04-28 19:47
Hey @peterkline-es, thanks for reporting. It looks like this is a duplicate of issue #987, which has been fixed already. The fix will be part of our next release.

**Closed by mlangkabel** 2020-04-28 19:47 UTC
