### ISSUE TITLE
Guide for debugging indexing errors

### ISSUE THREAD

**Issue by gvol** [CoatiSoftware/Sourcetrail#778] opened 2019-11-21 06:26 UTC
I'm trying to index my project (created from compile_commands.json) and the error message that I get is 

    The translation unit threw an exception during indexing. Please check if the source file conforms to the specified language standard and all necessary options are defined within your project setup.

I compile exactly as is in the compile_commands.json and it succeeds.  The logs show an incovation starting with "clang-tool", but I don't know where that is.  It doesn't seem to be the app anywhere.  I'm not sure how to debug this.  Any pointers, especially some pointers on how to invoke the indexer directly could be very helpful.

**Comment by egraether** [comment] 2019-11-21 07:05
Which platform do you use?

If you use **macOS**, please **download the [latest release](https://github.com/CoatiSoftware/Sourcetrail/releases) again** and try again. The build had a configuration issue that was exactly causing these problems.

Otherwise these errors likely mean that some project configuration causes the indexer to crash. Does your `compile_commands.json` contain a flag for the C++ standard e.g. `-std=gnu++14` for every file. If not please add the desired standard to the `Additional Compile Flags` in your project configuration.

**Comment by gvol** [comment] 2019-11-21 15:10
Sorry, I should have noted that I installed via `brew cask` (so on a Mac).  The version I have is 2019.4.61, which I think is the latest release.

I had an idea and ran the indexer in the main process, so that it crashed and then wanted to send a report to Apple, it had the following failure:

    Assertion failed: (Name.isIdentifier() && "Name is not a simple identifier"), function getName, file /Users/ebsi/Documents/clang-llvm/llvm/tools/clang/include/clang/AST/Decl.h, line 277.

So I now have a way to see what the problem is, though in this case I still don't know how to fix it (if I even can).

**Comment by mlangkabel** [comment] 2019-11-21 16:26
Looks like there is an assertion that triggers when we are trying to call `clang::NamedDecl::getName()` [here](https://github.com/llvm/llvm-project/blob/master/clang/include/clang/AST/Decl.h#L277).

Do you have a callstack for the crash?

**Comment by gvol** [comment] 2019-11-21 18:45
Unfortunately, there are no argument values that I can see.  I also haven't had time (and probably won't today) to get a minimal test case of a cpp file that fails.

```
* thread #18, stop reason = signal SIGABRT
  * frame #0: 0x00007fff65f872c6 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff66042bf1 libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff65ef16a6 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff65eba20d libsystem_c.dylib`__assert_rtn + 324
    frame #4: 0x0000000100f52f52 Sourcetrail`___lldb_unnamed_symbol221513$$Sourcetrail + 114
    frame #5: 0x0000000100f5356c Sourcetrail`CxxAstVisitorComponentIndexer::visitFunctionDecl(clang::FunctionDecl*) + 1324
    frame #6: 0x0000000100e92d23 Sourcetrail`CxxAstVisitor::VisitFunctionDecl(clang::FunctionDecl*) + 131
    frame #7: 0x0000000100eb5941 Sourcetrail`___lldb_unnamed_symbol215276$$Sourcetrail + 113
    frame #8: 0x0000000100eb64b5 Sourcetrail`___lldb_unnamed_symbol215329$$Sourcetrail + 53
    frame #9: 0x0000000100e8d1e2 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseCXXMethodDecl(clang::CXXMethodDecl*) + 82
    frame #10: 0x0000000100e8d0b5 Sourcetrail`CxxAstVisitor::TraverseCXXMethodDecl(clang::CXXMethodDecl*) + 165
    frame #11: 0x0000000100e89d04 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseDecl(clang::Decl*) + 3044
    frame #12: 0x0000000100e88d4a Sourcetrail`CxxAstVisitor::TraverseDecl(clang::Decl*) + 858
    frame #13: 0x0000000100f70d29 Sourcetrail`CxxVerboseAstVisitor::TraverseDecl(clang::Decl*) + 2441
    frame #14: 0x0000000100eaed8f Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseTemplateInstantiations(clang::FunctionTemplateDecl*) + 511
    frame #15: 0x0000000100e9f53b Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseFunctionTemplateDecl(clang::FunctionTemplateDecl*) + 331
    frame #16: 0x0000000100e89763 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseDecl(clang::Decl*) + 1603
    frame #17: 0x0000000100e88d4a Sourcetrail`CxxAstVisitor::TraverseDecl(clang::Decl*) + 858
    frame #18: 0x0000000100f70d29 Sourcetrail`CxxVerboseAstVisitor::TraverseDecl(clang::Decl*) + 2441
    frame #19: 0x0000000100e8cf08 Sourcetrail`CxxAstVisitor::traverseDeclContextHelper(clang::DeclContext*) + 200
    frame #20: 0x0000000100e8f8e3 Sourcetrail`CxxAstVisitor::TraverseClassTemplateSpecializationDecl(clang::ClassTemplateSpecializationDecl*) + 659
    frame #21: 0x0000000100e898f8 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseDecl(clang::Decl*) + 2008
    frame #22: 0x0000000100e88d4a Sourcetrail`CxxAstVisitor::TraverseDecl(clang::Decl*) + 858
    frame #23: 0x0000000100f70d29 Sourcetrail`CxxVerboseAstVisitor::TraverseDecl(clang::Decl*) + 2441
    frame #24: 0x0000000100ead696 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseTemplateInstantiations(clang::ClassTemplateDecl*) + 534
    frame #25: 0x0000000100e9f30b Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseClassTemplateDecl(clang::ClassTemplateDecl*) + 331
    frame #26: 0x0000000100e8972a Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseDecl(clang::Decl*) + 1546
    frame #27: 0x0000000100e88d4a Sourcetrail`CxxAstVisitor::TraverseDecl(clang::Decl*) + 858
    frame #28: 0x0000000100f70d29 Sourcetrail`CxxVerboseAstVisitor::TraverseDecl(clang::Decl*) + 2441
    frame #29: 0x0000000100ea7551 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseDeclContextHelper(clang::DeclContext*) + 209
    frame #30: 0x0000000100e9dff8 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseNamespaceDecl(clang::NamespaceDecl*) + 168
    frame #31: 0x0000000100e894b7 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseDecl(clang::Decl*) + 919
    frame #32: 0x0000000100e88d4a Sourcetrail`CxxAstVisitor::TraverseDecl(clang::Decl*) + 858
    frame #33: 0x0000000100f70d29 Sourcetrail`CxxVerboseAstVisitor::TraverseDecl(clang::Decl*) + 2441
    frame #34: 0x0000000100ea7551 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseDeclContextHelper(clang::DeclContext*) + 209
    frame #35: 0x0000000100ea3968 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseTranslationUnitDecl(clang::TranslationUnitDecl*) + 168
    frame #36: 0x0000000100e8a223 Sourcetrail`clang::RecursiveASTVisitor<CxxAstVisitor>::TraverseDecl(clang::Decl*) + 4355
    frame #37: 0x0000000100e88d4a Sourcetrail`CxxAstVisitor::TraverseDecl(clang::Decl*) + 858
    frame #38: 0x0000000100f70d29 Sourcetrail`CxxVerboseAstVisitor::TraverseDecl(clang::Decl*) + 2441
    frame #39: 0x0000000100e880c8 Sourcetrail`CxxAstVisitor::indexDecl(clang::Decl*) + 216
    frame #40: 0x0000000100e6f2b9 Sourcetrail`ASTConsumer::HandleTranslationUnit(clang::ASTContext&) + 57
    frame #41: 0x00000001012d6583 Sourcetrail`clang::ParseAST(clang::Sema&, bool, bool) + 531
    frame #42: 0x0000000101154190 Sourcetrail`clang::FrontendAction::Execute() + 128
    frame #43: 0x00000001010ec278 Sourcetrail`clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1496
    frame #44: 0x00000001010a7bef Sourcetrail`clang::tooling::FrontendActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) + 287
    frame #45: 0x00000001010a7a5a Sourcetrail`clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::__1::shared_ptr<clang::CompilerInvocation>, std::__1::shared_ptr<clang::PCHContainerOperations>) + 282
    frame #46: 0x00000001010a6b6b Sourcetrail`clang::tooling::ToolInvocation::run() + 3163
    frame #47: 0x00000001010a91ff Sourcetrail`clang::tooling::ClangTool::run(clang::tooling::ToolAction*) + 3551
    frame #48: 0x0000000100f64d97 Sourcetrail`CxxParser::runTool(clang::tooling::CompilationDatabase*, FilePath const&) + 2231
    frame #49: 0x0000000100f64027 Sourcetrail`CxxParser::buildIndex(std::__1::shared_ptr<IndexerCommandCxx>) + 1063
    frame #50: 0x0000000100e67cca Sourcetrail`IndexerCxx::doIndex(std::__1::shared_ptr<IndexerCommandCxx>, std::__1::shared_ptr<ParserClientImpl>, std::__1::shared_ptr<IndexerStateInfo>) + 314
    frame #51: 0x0000000100e3b789 Sourcetrail`___lldb_unnamed_symbol208289$$Sourcetrail + 1017
    frame #52: 0x0000000100365aab Sourcetrail`IndexerComposite::index(std::__1::shared_ptr<IndexerCommand>) + 251
    frame #53: 0x00000001003b0ca4 Sourcetrail`InterprocessIndexer::work() + 4724
    frame #54: 0x000000010036ea81 Sourcetrail`TaskBuildIndex::runIndexerThread(int) + 81
    frame #55: 0x0000000100378f68 Sourcetrail`___lldb_unnamed_symbol44569$$Sourcetrail + 136
    frame #56: 0x0000000100378ea7 Sourcetrail`___lldb_unnamed_symbol44566$$Sourcetrail + 87
    frame #57: 0x0000000100378aa6 Sourcetrail`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (TaskBuildIndex::*)(int), TaskBuildIndex*, int> >(void*) + 118
    frame #58: 0x00007fff660402eb libsystem_pthread.dylib`_pthread_body + 126
    frame #59: 0x00007fff66043249 libsystem_pthread.dylib`_pthread_start + 66
    frame #60: 0x00007fff6603f40d libsystem_pthread.dylib`thread_start + 13
```

**Comment by mlangkabel** [comment] 2019-11-21 18:46
Thanks for the stack. A minimal example would be awesome!

**Comment by egraether** [comment] 2019-11-21 19:24
**Please download the macOS build again**. This issue was caused by a configuration issue and was fixed by recompiling: https://github.com/CoatiSoftware/Sourcetrail/releases

**Comment by gvol** [comment] 2019-11-22 06:22
@egraether, you are absolutely right.  A new version solved the problem.  I'm sorry, I should have done it rather than assuming I had the newest version.  That said, a build version would be nice in addition to the release version to prevent this type of thing.

Anyway, I think some documentation on how to debug this sort of problem (I'm assuming similar things will come up in the future) would be useful, but I understand if you want to close this issue.  

Thanks for your help!

**Closed** 2019-12-09 12:34 UTC

**Comment by enhering** [comment] 2020-10-26 12:47
Hi! I'm using MacOS 10.13.6 and SourceTrail 2020.2.43 and I'm getting this very same error at the beginning of every C++ file. Have you got any idea on what can be the issue?
