### ISSUE TITLE
Remote Source Indexing

### ISSUE THREAD

**Issue by merrychap** [CoatiSoftware/Sourcetrail#1163] opened 2021-03-10 18:33 UTC
Is Sourcetrail available to index files using a remote server?
For example, I have my local machine and some powerful (CPU and memory) remote host. I would like to work with Sourcetrail on my local machine while indexing and searching are happening on the remote host. It will save the hardware resources of a local machine if the target project has some huge source code database.

```

        Local host                         Remote host
+-------------------------+           +-----------------------+
| Local machine with      |           | Indexing and source   |
| Sourcetrail source code +---------->| code searching happen |
| window                  |           | on the remote machine |
+-------------------------+           +-----------------------+
```

Thank you in advance!

**Comment by mlangkabel** [comment] 2021-03-13 05:40
Hi @merrychap, it looks like this is a duplicate of #134, so I will close this issue now. Over there is a suggestion of using Sourcetrail's command line interface to set up the remote indexing. If you have some more feedback or suggestions for the remote indexing, it would be best to add it there.

**Closed by mlangkabel** 2021-03-13 05:40 UTC
