### ISSUE TITLE
Cannot create Sourcetrail project in folder with dashes/dots in path

### ISSUE THREAD

**Issue by viknat** [CoatiSoftware/Sourcetrail#1018] opened 2020-05-20 06:07 UTC
Sourcetrail version: 2020.1.117
Platform: Mac OS Mojave

When creating a new Python project using the UI, project creation fails if there are any dots or dashes in the path with the following error message:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/5532863/82410703-39a7ff00-9a25-11ea-9928-c13271ad027f.png">

However, it works fine if I symlink the path so that the full path including the symlink no longer contains dots or dashes.

Let me know if log outputs/any other info would be useful.

Thanks!

**Comment by mlangkabel** [comment] 2020-05-22 07:35
Thanks for reporting. This is a duplicate of #1001. So I will close this now.

**Closed by mlangkabel** 2020-05-22 07:35 UTC
Labels: duplicate
